/**:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names: !!python/tuple
    - controller_server
    - planner_server
    - recoveries_server
    - waypoint_follower
    - bt_navigator
